#!/bin/bash

echo "Copy ace editor code"

cp -R  ~/app-root/data/ace-builds-1.2.0 ~/app-root/repo/web/ui

echo "Copy Emscripten data"

cp -R ~/app-root/data/emscripten_app ~/app-root/repo/web

echo "Copy openshift weconfig"

cp -f ~/app-root/data/webconfig.php ~/app-root/repo/web/conf

echo "Compute gzipped size"

export EMSCRIPTEN_APP_SIZE=$(gzip -c ~/app-root/data/emscripten_app/oflive.js | wc -c)

export EMSCRIPTEN_DATA_SIZE=$(gzip -c ~/app-root/data/emscripten_app/oflive.data | wc -c)
